### ISSUE TITLE
AFK Kick Deletes Survival Inventory

### ISSUE THREAD

**Issue by NQNStudios** [cmu-rl/mc_plugin#12]
Steps to reproduce:
1. Log on to the server
2. Enter Survival mode through the hub portal
3. Pick up a dirt block or mushroom (just to quickly get something in your inventory)
4. Don't touch controls until receiving the AFK kick
5. Log back in and head to survival. Observe missing items and experience levels

**Comment by ccodel** [comment]
I tested today, November 4, after pushing changes on Thursday, November 1. I kept survival inventory on AFK kick, direct world move, and server logout in offline mode, which we will keep the server at.
